### ISSUE TITLE
Cut a post 1.2.4 Release

### ISSUE THREAD

**Issue by berney** [geerlingguy/ansible-role-packer-debian#10]
Commit a0848db is in master post 1.2.4 release which is the latest published here and on ansible-galaxy. Trying to use `packer` with VMware ESXi is breaking on this role. Error is: -

```
TASK [geerlingguy.packer-debian : Mount VMware tools.] *************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /tmp/vmfusion: mount special device /home/vagrant/linux.iso does not exist\n"}
```

I had to type out the above as I can't copy/paste from that environment, so it might have typos/omissions.

The above tasks are in vmware.yml and would be skipped post a0848db on a  Ubuntu 16.04 install. I added a debug pre_task to confirm that ansible_distribution_version is 16.04.

**Comment by berney** [comment]
I changed the `requirements.yml` file in https://github.com/geerlingguy/packer-ubuntu-1604 to pull from git and the install worked successfully, save for the vagrant post-processor which is a bug in Packer.

**Comment by geerlingguy** [comment]
Sorry about that! Just cut 1.2.5, should be on Galaxy once tests pass.
