### ISSUE TITLE
Support for Hyper-V ?

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/ansible-role-packer-debian#14]
Hi

I start work to add support for Hyper-V boxes to your packer-ubuntu1604 and packer-ubuntu1404.

What do you think about include that feature in your role?

**Comment by geerlingguy** [comment]
That would be great—what kinds of things would need to be done in this role, specifically? (e.g. the split between this role and the packer configuration projects)

**Comment by it-praktyk** [comment]
To support Hyper-V too is needed
- add detecting of Hyper-V environment
- add distribution specific tasks to install Hyper-V aware kernel (e.g. linux-tools-virtual-lts-xenial, linux-cloud-tools-virtual-lts-xenial) or install components from Linux Integration Services.

My first experience with Hyper-V builder in Packer are not positive - builds fail due to not implemented ssh_timeout. I've found some other bugs too.

[Supported Ubuntu virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)
[Supported Debian virtual machines on Hyper-V](https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-debian-virtual-machines-on-hyper-v)
[Linux Integration Services Version 4.1 for Hyper-V](https://www.microsoft.com/en-us/download/details.aspx?id=51612)

**Comment by it-praktyk** [comment]
[Currently unresolved bugs for Packer Hyper-V builder](https://github.com/hashicorp/packer/issues?q=is%3Aissue+is%3Aopen+label%3Abuilder%2Fhyperv) don't allow reliably build boxes.
