### ISSUE TITLE
TASK [geerlingguy.packer-debian : Mount VMware tools.] failure

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/ansible-role-packer-debian#27]
Using your project from https://github.com/geerlingguy/packer-boxes.git and VMware Fusion as a builder. Get to the Mount VMware tools and the task fails.

fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error mounting /tmp/vmfusion: mount: /tmp/vmfusion: special device /home/vagrant/linux.iso does not exist.\n"}

Guessing it's because the default.yml sets 

vmware_install_open_vm_tools: no

But I'd assume the role should work with the VMware provided tools too?

<edit>
Command invoked like this

$ packer build -var 'version=1.0' -except vagrant-cloud -only=vmware-iso  box-config.json

VMware Fusion Professional 11.5.3
macOS Mojave 10.14.6

**Comment by pbicskei** [comment]
> 
> 
> Using your project from https://github.com/geerlingguy/packer-boxes.git and VMware Fusion as a builder. Get to the Mount VMware tools and the task fails.
> 
> fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error mounting /tmp/vmfusion: mount: /tmp/vmfusion: special device /home/vagrant/linux.iso does not exist.\n"}
> 
> Guessing it's because the default.yml sets
> 
> vmware_install_open_vm_tools: no
> 
> But I'd assume the role should work with the VMware provided tools too?
> Command invoked like this
> 
> $ packer build -var 'version=1.0' -except vagrant-cloud -only=vmware-iso box-config.json
> 
> VMware Fusion Professional 11.5.3
> macOS Mojave 10.14.6


In the packer json, add `"tools_upload_flavor": "linux"` to the vmware-iso builder to resolve your issue.

It simply does not have the tools iso, as its playbook step does not appear to implement open-vm-tools.
