### ISSUE TITLE
HGFS kernel module not found, so Vagrant does not up the box

### ISSUE THREAD

**Issue by NathanDotTo** [geerlingguy/ansible-role-packer-debian#8]
Hi

I am using this role in the project: https://github.com/DevOps4Networks/iox-utils/tree/master/iox-dev-vm, which is based on this project: https://github.com/geerlingguy/packer-ubuntu-1404. Thank you for doing this work.

The Packer build creates the VMware Box, but when I attempt to up it I get:

```
The HGFS kernel module was not found on the running virtual machine. This must be installed for shared
 folders to work properly. Please install the VMware tools within the guest and try again. Note that the
 VMware tools installation will succeed even if HGFS fails to properly install. Carefully read the output of
 the VMware tools installation to verify the HGFS kernel modules were installed properly.
```

Looking back at the Packer build with Ansible debug turned on, I see:

```
For kernels >= 4.0.0, open-vm-tools need to be of version 10.0.0 or higher for ", "VMware Host Guest 
Filessystem (vmhgfs) to function with VMware Tools. Please ", "upgrade open-vm-tools and rerun this 
installer, or uninstall open-vm-tools. ", "Alternatively, you can disable using the vmhgfs when VMware 
Tools are ", "configured.", "", "Enter yes to proceed. [no] ", "", "Execution aborted."], "warnings": []}
```

In this role I see:

```
---
- name: Install VMware tools.
  apt: name=open-vm-tools state=installed
```

I then look at:

http://packages.ubuntu.com/trusty/open-vm-tools

Which seems to imply that the latest version available for Trusty/14.04 LTS, is 9.4.0, which won't work according to the instructions above.

I am not sure what the best fix would be here, so I am opening this issues to discuss it with you.

Regards

Nathan

**Comment by geerlingguy** [comment]
Hmm... looks like I may need to find a better way to install `open-vm-tools`. Is there an apt repo/ppa that has later versions?

**Comment by geerlingguy** [comment]
Also note that you can switch the default `/vagrant` synced folder to use NFS or some other method besides native shared folders to temporarily bypass this issue. See, for example: https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L106

**Comment by NathanDotTo** [comment]
Hi

See https://github.com/DevOps4Networks/iox-utils/blob/master/iox-dev-vm/scripts/ansible.sh

Where I have:

#Install a key for VMware repo
wget https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-RSA-KEY.pub
apt-key add VMWARE-PACKAGING-GPG-RSA-KEY.pub
wget https://packages.vmware.com/tools/keys/VMWARE-PACKAGING-GPG-DSA-KEY.pub
apt-key add VMWARE-PACKAGING-GPG-DSA-KEY.pub

#Add VMware repo
apt-add-repository 'deb http://packages.vmware.com/packages/ubuntu precise main'
apt-get -y update

And https://github.com/DevOps4Networks/ansible-role-packer-debian/blob/master/tasks/vmware.yml

Where I have:

- name: Install VMware tools.
  apt: name=open-vm-tools-deploypkg state=present

That *seems* to get rid of the error messages during the install phase, but the HGFS kernel module is still not loading upon startup.

Regards

Nathan

**Comment by geerlingguy** [comment]
Vagrant 1.8.4 might resolve this issue after an update I will push that adds the following task:

```yaml
- name: Create /mnt/hgfs directory for synced folder mounts.
  file:
    path: /mnt/hgfs
    state: directory
```

I'm testing right now for https://github.com/geerlingguy/packer-ubuntu-1404/issues/18

**Comment by geerlingguy** [comment]
14.04.4 still doesn't work (hangs at the HGFS kernel module issue). See: https://github.com/geerlingguy/packer-ubuntu-1404/issues/18#issuecomment-227321862

**Comment by geerlingguy** [comment]
For 14.04, you have to currently use 14.04.1 (14.04.4 won't build correctly). 16.04 now works correctly, woohoo!
